//
// Generated file, do not edit! Created by opp_msgtool 6.1 from src/org/advlgs/ADVLGSMessage.msg.
//

#ifndef __ADVLGS_ADVLGSMESSAGE_M_H
#define __ADVLGS_ADVLGSMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace advlgs {

class ADVLGSMessage;

}  // namespace advlgs

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace advlgs {

/**
 * Class generated from <tt>src/org/advlgs/ADVLGSMessage.msg:6</tt> by opp_msgtool.
 * <pre>
 * packet ADVLGSMessage extends veins::BaseFrame1609_4
 * {
 *     string demoData;
 *     veins::LAddress::L2Type senderAddress = -1;
 *     int serial = 0;
 *     simtime_t generatedAt;
 *     simtime_t signedAt;
 *     simtime_t sentAt;
 *     double signDurationSeconds = 0;
 *     string serviceDomain;
 *     string signature;
 *     string linkTag;
 * }
 * </pre>
 */
class ADVLGSMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string demoData;
    ::veins::LAddress::L2Type senderAddress = -1;
    int serial = 0;
    ::omnetpp::simtime_t generatedAt = SIMTIME_ZERO;
    ::omnetpp::simtime_t signedAt = SIMTIME_ZERO;
    ::omnetpp::simtime_t sentAt = SIMTIME_ZERO;
    double signDurationSeconds = 0;
    ::omnetpp::opp_string serviceDomain;
    ::omnetpp::opp_string signature;
    ::omnetpp::opp_string linkTag;

  private:
    void copy(const ADVLGSMessage& other);

  protected:
    bool operator==(const ADVLGSMessage&) = delete;

  public:
    ADVLGSMessage(const char *name=nullptr, short kind=0);
    ADVLGSMessage(const ADVLGSMessage& other);
    virtual ~ADVLGSMessage();
    ADVLGSMessage& operator=(const ADVLGSMessage& other);
    virtual ADVLGSMessage *dup() const override {return new ADVLGSMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getDemoData() const;
    virtual void setDemoData(const char * demoData);

    virtual const ::veins::LAddress::L2Type& getSenderAddress() const;
    virtual ::veins::LAddress::L2Type& getSenderAddressForUpdate() { return const_cast<::veins::LAddress::L2Type&>(const_cast<ADVLGSMessage*>(this)->getSenderAddress());}
    virtual void setSenderAddress(const ::veins::LAddress::L2Type& senderAddress);

    virtual int getSerial() const;
    virtual void setSerial(int serial);

    virtual ::omnetpp::simtime_t getGeneratedAt() const;
    virtual void setGeneratedAt(::omnetpp::simtime_t generatedAt);

    virtual ::omnetpp::simtime_t getSignedAt() const;
    virtual void setSignedAt(::omnetpp::simtime_t signedAt);

    virtual ::omnetpp::simtime_t getSentAt() const;
    virtual void setSentAt(::omnetpp::simtime_t sentAt);

    virtual double getSignDurationSeconds() const;
    virtual void setSignDurationSeconds(double signDurationSeconds);

    virtual const char * getServiceDomain() const;
    virtual void setServiceDomain(const char * serviceDomain);

    virtual const char * getSignature() const;
    virtual void setSignature(const char * signature);

    virtual const char * getLinkTag() const;
    virtual void setLinkTag(const char * linkTag);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ADVLGSMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ADVLGSMessage& obj) {obj.parsimUnpack(b);}


}  // namespace advlgs


namespace omnetpp {

template<> inline advlgs::ADVLGSMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<advlgs::ADVLGSMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __ADVLGS_ADVLGSMESSAGE_M_H

